### ISSUE TITLE
Data access logic in controller

### ISSUE THREAD

**Issue by rogertinsley** [dstewart101/ToDoMVC#1]
This is considered an antipattern.

All data access code is consider a `model` in the `MVC`.

If you move this to the Model, then it means you can reuse this in a `Web API` without having to duplicate logic.

**Comment by dstewart101** [comment]
Data Access removed from controller. 
IToDoRepository set up with basic CRUD methods. ToDoRepository implements IToDoRepository.

**Comment by dstewart101** [comment]
in
