### ISSUE TITLE
Inversion of control container

### ISSUE THREAD

**Issue by rogertinsley** [dstewart101/ToDoMVC#2]
You want to look at IOC containers.

[Ninject](https://github.com/ninject/Ninject) is a popular one.

**Comment by rogertinsley** [comment]
Get rid of this:

```c#
private IToDoRepository todoRepository;

public ToDosController() { 
    this.todoRepository = new ToDoRepository(new ToDoContext());
}
```

and replace with

```c#
private IToDoRepository todoRepository;

public ToDosController(IToDoRepository repository) { 
    this.todoRepository = repository;
}
```

https://github.com/dstewart101/ToDoMVC/blob/master/ToDoMVC/Controllers/ToDosController.cs#L19

You'll need to add a DI container as there is now no parameterless constructor in the controll0r.

:sunrise:

**Comment by dstewart101** [comment]
what's the problem with the way I have it now?
but have you got a headline for the problem?
is there bad news about a parameterless constructor?
i'm going to read about ninject - but is there something i should keep in mind while i do it?

**Comment by rogertinsley** [comment]
Separation of concerns promote coding against interfaces, so you can swap out implementations and even use a mocking framework for testing.

So how would you inject in a fake implementation of your IRepository?

You can't, the good practice bible :trollface: says to inject the dependency via the construct0r. like above.

you need a framework to instantiate your dependency chain - so take a look at Ninject.

**Comment by dstewart101** [comment]
ninject is in. closing this one off.
thanks.
